services:
  server:
    build:
      context: .
      target: build-base
    ports:
      - "1313:1313"
    entrypoint: ["hugo", "server", "--bind", "0.0.0.0"]
    develop:
      watch:
        - action: sync
          path: .
          target: /project
